finder/findR/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "findR"
urlpatterns = [
    path("", views.index, name="index"),
    path(
        "login",
        auth_views.LoginView.as_view(template_name="login.html"),
        name="login",
    ),
    path(
        "logout",
        auth_views.LogoutView.as_view(template_name="base.html"),
        name="logout",
    ),
    path("register", views.register, name="register"),
    path("add_listing", views.add_listing, name="add_listing"),
    path("browse", views.browse, name="browse")

]

finder/finder/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("findR.urls"))
]

finder/findR/models.py
from django.db import models

# Create your models here.


from django.contrib.auth.models import User

class ItemListings(models.Model):
    id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    photo_path = models.CharField(max_length=200)
    image = models.FileField(upload_to="images/")
    longitutude = models.FloatField()
    latitude = models.FloatField()
    status = models.CharField(max_length=1)
    rating = models.IntegerField()
    title = models.CharField(max_length=200)
    decription = models.CharField(max_length=500)
    

finder/findR/views.py
from django.shortcuts import render
from django.core.files.storage import FileSystemStorage

from .models import ItemListings, User
# Create your views here.

from django.contrib.auth.hashers import make_password

def index(request):
    return render(request, "home.html")


def register(request):
    if(request.method == "POST"):
        User.objects.create_user(
            username=request.POST["username"],
            password=request.POST["password"],
            email=request.POST["email"],
            first_name=request.POST["first_name"],
            last_name=request.POST["last_name"],
        )
        return render(request, "login.html")
    else:
        return render(request, "register.html")

def login(request):
    if(request.method == "POST"):
        print(request.POST)
        try:
            user = User.objects.get(username=request.POST["username"])
            print("hashed password is: ", make_password(request.POST["password"]))
            print("password stored is: ", user.password)
            if(user.check_password(make_password(request.POST["password"]))):
                user.is_authenticated = True
                return render(request, "add_listing.html")
            else:
                message = "Invalid password"
                return render(request, "login.html", {"message": message})
        except:
            message = "Username doesn't exist"
            return render(request, "login.html", {"message": message})
    elif(request.method == "GET"):
        return render(request, "login.html")

def add_listing(request):
    if (request.method == "POST" and request.FILES['post-photos']):
        user = User.objects.get(username=request.user) 
        upload = request.FILES['post-photos']       # Image object that was uploaded through the form
        fss = FileSystemStorage()                   # File System Storage object
        file = fss.save(upload.name, upload)        # Saving the image object using File System Storage object method
        file_url = fss.url(file)                    # Finding the image url in file system
        ItemListings.objects.create(
        user_id=user,
        photo_path=file_url,
        image=upload,
        longitutude=request.POST["post-longitude"],
        latitude=request.POST["post-latitude"],
        status='A',
        rating=0,
        title=request.POST["post-title"],
        )
        message = "Listing added"
        return render(request, "add_listing.html", {"message": message, "file_url": file_url})
    message = "Invalid username"
    return render(request, "add_listing.html")
        

def browse(request):
    if(request.method == "POST"):
        try:
            print(request.POST)
            if request.POST["tags"] != "":
                items = ItemListings.objects.filter(
                    latitude__range=(float(request.POST["post-latitude"])-1,float(request.POST["post-latitude"])+1),
                    longitutude__range=(float(request.POST["post-longitude"])-1,float(request.POST["post-longitude"])+1),
                    title__contains=request.POST["tags"]
                )
            else: 
                items = ItemListings.objects.filter(
                    latitude__range=(float(request.POST["post-latitude"])-1,float(request.POST["post-latitude"])+1),
                    longitutude__range=(float(request.POST["post-longitude"])-1,float(request.POST["post-longitude"])+1)
                )
            print(items)
            return render(request, "browse.html", {"items": items})
        except Exception as e:
            print(e)
            message = "Invalid username"
            return render(request, "browse.html", {"message": message})
            
    else:
        return render(request, "browse.html")

finder/findR/templates/index.html
{% extends 'base.html' %}

templates/add_listing.html
<!-- add a post to the web page with photo and location and other details -->
{% extends 'base.html' %}

{% block content %}
<div>
	<script src="https://maps.googleapis.com/maps/api/js?key=&&callback=initMap"></script>
    <style>
		.preview {
			display: flex;
			flex-wrap: wrap;
			max-width: 500px;
		}
		.preview img {
			max-width: 150px;
			max-height: 150px;
			margin: 10px;
		}
	</style>
    <title>Add an item for donating</title>
	<iframe id="map" width="600" height="450" frameborder="0" style="border:0"
    src="https://www.google.com/maps/embed/v1/view?key=&zoom=14"
    allowfullscreen></iframe>
	<form action="#" method="POST" enctype="multipart/form-data">
		{% csrf_token %}

		<label for="post-title">Tell us what is it you are donating:</label><br>
		<input type="text" id="post-title" name="post-title"><br>

		<label for="post-photos">Photos:</label><br>
		<input type="file" id="post-photos" name="post-photos" accepts="image/*" multiple onchange="previewPhotos(event)"><br>
		<div class="preview"></div>

		<label for="post-latitude">Latitude:</label><br>
		<input type="text" id="post-latitude" name="post-latitude" readonly="true"><br>

        <label for="post-longitude">Longitude:</label><br>
		<input type="text" id="post-longitude" name="post-longitude" readonly="true"><br>

		<input type="submit" value="Submit">
	</form>

	<h2>Uploaded File</h2>
	<div>
		{% if file_url %}
		<div>
			<p>Uploaded to:<a href="{{ file_url }}">{{ file_url }}</a></p>
			<img src="{{ file_url }}" class="img-fluid">
		</div>
		{% else %}
		<p> No Picture Added </p>
		{% endif %}
	</div>


	<script>
		function previewPhotos(event) {
			const previewContainer = document.querySelector('.preview');
			previewContainer.innerHTML = '';
			const files = event.target.files;
			for (let i = 0; i < files.length; i++) {
				const file = files[i];
				const reader = new FileReader();
				reader.readAsDataURL(file);
				reader.onload = function() {
					const img = document.createElement('img');
					img.src = reader.result;
					previewContainer.appendChild(img);
				}
			}
		}
		navigator.geolocation.getCurrentPosition(function(position) {
          var latitude = 40.694682;
          var longitude = -73.9858714;
          latitude = position.coords.latitude;
          longitude = position.coords.longitude;
		  var post_latitude = document.getElementById("post-latitude");
		  post_latitude.value = latitude;
		  var post_longitude = document.getElementById("post-longitude");
		  post_longitude.value = longitude;
          // Set the center of the map to the user's location
          const map = document.getElementById('map');
          const url = new URL(map.src);
          url.searchParams.set('center', `${latitude},${longitude}`);
          map.src = url.toString();
        });
        
	</script>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <title>{% block title %}Findr{% endblock %}</title>
    {% endblock %}
    {% block headscripts %}
    {% endblock %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <style>
    h1 {
        font-family: Futura, Helvetica, sans-serif;
    }
    </style>
</head>
<body>

<div style="background-color: #678CAD;" class="p-5 text-white text-center">
  <h1>FINDR</h1>
  <p class="fst-italic">Find and post items you find out on the street!</p>
</div>

{% if not user.is_authenticated %}
<nav class="navbar navbar-expand-sm bg-light navbar-light sticky-top">
    <div class="container-fluid">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{%url 'findR:index' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{%url 'findR:browse' %}">Browse</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{%url 'findR:login' %}">Log in</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{%url 'findR:register' %}">Register</a>
            </li>
        </ul>
    </div>
</nav>
{% endif %}
{% if user.is_authenticated %}
<nav class="navbar navbar-expand-sm bg-light navbar-light sticky-top">
    <div class="container-fluid">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{%url 'findR:index' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{%url 'findR:browse' %}">Browse</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{%url 'findR:add_listing' %}">Post</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{%url 'findR:logout' %}">Log Out</a>
            </li>
        </ul>
    </div>
</nav>
{% endif %}

<div id="root">{% block content %} {% endblock %}</div>

</body>
</html>

templates/browse.html
{% extends "base.html" %}

{% block content %}

<div class="text-center">
	<h2>Browsing Posts</h2>
	<p> Your present location is around this place.</p>
	<iframe id="map" width="600" height="450" frameborder="0" style="border:0"
    src="https://www.google.com/maps/embed/v1/view?key=&zoom=14"
    allowfullscreen></iframe>
	<form action="#" method="POST">
		{% csrf_token %}
		<label for="filter-location">Location:</label>
		<input type="text" id="post-latitude" name="post-latitude" readonly="true">
		<span>° ,</span>
		<input type="text" id="post-longitude" name="post-longitude" readonly="true">
		<span>°</span>

		<br><br>

		<label for="filter-tags">Tags:</label>
		<input type="text" id="filter-tags" name="tags">
		<br>
		<br>

		<input type="submit" value="Find" class="btn btn-primary" style="background-color: #678CAD;">
	</form>
	{% if items %}
		{% for item in items %}
			<div>
				<h2>{{ item.title }}</h2>
				<p>Location: {{ item.latitude }}, {{ item.longitutude }}</p>
				<p>Photo:</p>
					<img src="{{ image.url }}" class="img-fluid">
			</div>
		{% endfor %}
	{% else %}
		<p> No items found </p>
	{% endif %}
	<hr>
	<script src="https://maps.googleapis.com/maps/api/js?key=&&callback=initMap"></script>
	<script>
		navigator.geolocation.getCurrentPosition(function(position) {
          var latitude = 40.694682;
          var longitude = -73.9858714;
          latitude = position.coords.latitude;
          longitude = position.coords.longitude;
		  var post_latitude = document.getElementById("post-latitude");
		  post_latitude.value = latitude;
		  var post_longitude = document.getElementById("post-longitude");
		  post_longitude.value = longitude;
          // Set the center of the map to the user's location
          const map = document.getElementById('map');
          const url = new URL(map.src);
          url.searchParams.set('center', `${latitude},${longitude}`);
          map.src = url.toString();
        });
        
	</script>
	</script>
	
</div>

{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block content %}

<div
  class="bg-image d-flex text-center mb-1 justify-content-center align-items-center"
  style="background-image: url('https://rare-gallery.com/uploads/posts/502752-new-york-city.jpg');
  height: 100vh; background-position:top;"
>
    <h2 style="color: white; font-size: 5rem;" ><b>Welcome to Findr!</b><br><a style="color: white; font-size: 2rem;" href="{%url 'findR:browse' %}">Click here to start browsing</a></h2>
</div>

{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}

<h2 class="text-center">Login</h2>
<div class="d-flex justify-content-center align-items-center">
    <form action="{% url 'findR:login' %}" class="login" method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="username" class="form-label">Username</label>
            <input type = "text", id="username", name="username">
        </div>
        <div>
            <label for="password" class="form-label">Password</label>
            <input type = "password", id="password", name="password">
        </div>
        <input type="submit" class="btn btn-primary" style="background-color: #678CAD;">
    </form>
</div>
{% if message %}
<p> {{ message }} </p>
{% endif %}


{% endblock %}

templates/register.html
{% extends 'base.html' %}



{% block content %}
<h2 class="text-center">Register</h2>
<div class="d-flex justify-content-center align-items-center">
    <form method="POST" action="{% url 'findR:register' %}">
        {% csrf_token %}
            <label for="username">Username</label>
            <input type="text" name="username" id="username" required>
            <br>
            <br>
            <label for="email">Email</label>
            <input type="email" name="email" id="email" required>
            <br>
            <br>
            <label for="first_name"> First Name</label>
            <input type="text" name="first_name" id="first_name" required>
            <br>
            <br>
            <label for="last_name"> Last Name</label>
            <input type="text" name="last_name" id="last_name" required>
            <br>
            <br>
            <label for="password">Password</label>
            <input type="password" name="password" id="password" required>
            <br>
            <br>
            <label for="password2">Confirm Password</label>
            <input type="password" name="password2" id="password2" required>
            <br>
            <br>
            <input type="submit" value="Register" class="btn btn-primary" style="background-color: #678CAD;">

    </form>
        


</div>
{% endblock %}